import {
  Product,
  Customer,
  Vendor,
  SalesOrder,
  PurchaseOrder,
  Invoice,
  Expense,
  ApprovalItem,
  Notification,
  DashboardKPIs,
  AIInsight,
} from '../types/erp';
import { User } from '../types/auth';

export const mockCurrentUser: User = {
  id: 'usr-101',
  name: 'Ganesh Kanaki',
  email: 'iamganeshkanaki@gmail.com',
  role: 'Admin',
  company: 'Apex Global Enterprises Ltd',
  branch: 'Silicon Valley HQ',
  department: 'Executive Operations',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  permissions: [
    'sales.view',
    'sales.create',
    'purchase.view',
    'purchase.create',
    'purchase.approve',
    'inventory.view',
    'inventory.adjust',
    'finance.view',
    'finance.approve',
    'hr.view',
    'ai.use',
    'settings.manage',
  ],
};

export const mockKPIs: DashboardKPIs = {
  salesToday: 428500,
  salesGrowth: 14.8,
  purchasesThisMonth: 1250000,
  purchasesGrowth: -4.2,
  revenue: 8940000,
  revenueGrowth: 18.5,
  expenses: 3120000,
  expensesGrowth: 2.1,
  receivables: 1840000,
  payables: 920000,
  inventoryValue: 14650000,
  pendingApprovalsCount: 5,
};

export const mockInsights: AIInsight[] = [
  {
    id: 'ins-1',
    title: '7 products below reorder level',
    type: 'warning',
    description: 'High-velocity SKUs including Industrial Sensor B3 and Titanium Bearings will stock out in 4 days.',
    metric: '7 Critical SKUs',
    actionLabel: 'Draft Reorder PO',
    actionPrompt: 'Create a purchase order for low stock items',
  },
  {
    id: 'ins-2',
    title: '3 high-value invoices overdue (> 30 days)',
    type: 'warning',
    description: 'Outstanding overdue receivables total ₹4,60,000 from Zenith Tech and Orion Logistics.',
    metric: '₹4,60,000 Overdue',
    actionLabel: 'Send Reminders',
    actionPrompt: 'Show overdue invoices and send reminders',
  },
  {
    id: 'ins-3',
    title: 'Sales velocity up 18.5% vs previous month',
    type: 'positive',
    description: 'Electronic modules and hydraulic components exceeded monthly quota by 22%.',
    metric: '+18.5% Growth',
    actionLabel: 'View Sales Report',
    actionPrompt: 'Compare sales with last month',
  },
  {
    id: 'ins-4',
    title: '5 operational approvals pending your sign-off',
    type: 'action',
    description: 'Includes ABC Traders PO (₹1,20,000) and Q3 Equipment Maintenance reimbursement.',
    metric: '5 Action Items',
    actionLabel: 'Open Approvals',
    actionPrompt: 'Show pending approvals',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'PRD-001',
    sku: 'SKU-ELEC-409',
    name: 'Industrial Sensor Module B3',
    category: 'Electronics',
    stockQty: 14,
    reorderLevel: 50,
    unitPrice: 4500,
    warehouse: 'Main Central Hub',
    status: 'Low Stock',
    lastUpdated: '2026-09-18',
  },
  {
    id: 'PRD-002',
    sku: 'SKU-MECH-882',
    name: 'Precision Titanium Bearing Set',
    category: 'Mechanical',
    stockQty: 8,
    reorderLevel: 25,
    unitPrice: 8900,
    warehouse: 'West Coast Depo',
    status: 'Low Stock',
    lastUpdated: '2026-09-17',
  },
  {
    id: 'PRD-003',
    sku: 'SKU-HYDR-110',
    name: 'High-Pressure Hydraulic Valve 250bar',
    category: 'Hydraulics',
    stockQty: 180,
    reorderLevel: 40,
    unitPrice: 12400,
    warehouse: 'Main Central Hub',
    status: 'In Stock',
    lastUpdated: '2026-09-19',
  },
  {
    id: 'PRD-004',
    sku: 'SKU-AUTO-601',
    name: 'Programmable Logic Controller (PLC-V2)',
    category: 'Automation',
    stockQty: 42,
    reorderLevel: 20,
    unitPrice: 38500,
    warehouse: 'East Bay Logistics',
    status: 'In Stock',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'PRD-005',
    sku: 'SKU-RAW-304',
    name: 'Seamless Stainless Steel Tubing 316L',
    category: 'Raw Materials',
    stockQty: 0,
    reorderLevel: 100,
    unitPrice: 2800,
    warehouse: 'Main Central Hub',
    status: 'Out of Stock',
    lastUpdated: '2026-09-14',
  },
  {
    id: 'PRD-006',
    sku: 'SKU-POW-909',
    name: 'Brushless DC Motor 48V 1.5kW',
    category: 'Power & Motors',
    stockQty: 65,
    reorderLevel: 15,
    unitPrice: 19800,
    warehouse: 'West Coast Depo',
    status: 'In Stock',
    lastUpdated: '2026-09-19',
  },
  {
    id: 'PRD-007',
    sku: 'SKU-ELEC-550',
    name: 'Optocoupler Relay Board 16CH',
    category: 'Electronics',
    stockQty: 320,
    reorderLevel: 80,
    unitPrice: 1650,
    warehouse: 'East Bay Logistics',
    status: 'In Stock',
    lastUpdated: '2026-09-12',
  },
];

export const mockSalesOrders: SalesOrder[] = [
  {
    id: 'SO-8921',
    orderNumber: 'SO-2026-8921',
    customerName: 'Nexis Aerospace Dynamics',
    date: '2026-09-19',
    itemsCount: 8,
    totalAmount: 420000,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Shipped',
  },
  {
    id: 'SO-8922',
    orderNumber: 'SO-2026-8922',
    customerName: 'Quantum Solar Systems Ltd',
    date: '2026-09-18',
    itemsCount: 14,
    totalAmount: 380000,
    paymentStatus: 'Pending',
    fulfillmentStatus: 'Confirmed',
  },
  {
    id: 'SO-8923',
    orderNumber: 'SO-2026-8923',
    customerName: 'Orion Advanced Robotics',
    date: '2026-09-18',
    itemsCount: 4,
    totalAmount: 185000,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Delivered',
  },
  {
    id: 'SO-8924',
    orderNumber: 'SO-2026-8924',
    customerName: 'Zenith Marine Works',
    date: '2026-09-17',
    itemsCount: 22,
    totalAmount: 760000,
    paymentStatus: 'Overdue',
    fulfillmentStatus: 'Delivered',
  },
  {
    id: 'SO-8925',
    orderNumber: 'SO-2026-8925',
    customerName: 'Vanguard Instruments',
    date: '2026-09-16',
    itemsCount: 6,
    totalAmount: 94000,
    paymentStatus: 'Partial',
    fulfillmentStatus: 'Confirmed',
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'PO-4401',
    poNumber: 'PO-2026-4401',
    vendorName: 'ABC Traders & Supplies',
    issueDate: '2026-09-19',
    expectedDate: '2026-09-24',
    totalAmount: 120000,
    status: 'Waiting Approval',
  },
  {
    id: 'PO-4402',
    poNumber: 'PO-2026-4402',
    vendorName: 'MicroChip Foundry Int',
    issueDate: '2026-09-17',
    expectedDate: '2026-09-28',
    totalAmount: 485000,
    status: 'Approved',
  },
  {
    id: 'PO-4403',
    poNumber: 'PO-2026-4403',
    vendorName: 'Continental Steels Corp',
    issueDate: '2026-09-15',
    expectedDate: '2026-09-20',
    totalAmount: 310000,
    status: 'Received',
  },
  {
    id: 'PO-4404',
    poNumber: 'PO-2026-4404',
    vendorName: 'HydraTech Fluid Dynamics',
    issueDate: '2026-09-14',
    expectedDate: '2026-09-22',
    totalAmount: 85000,
    status: 'Approved',
  },
];

export const mockApprovals: ApprovalItem[] = [
  {
    id: 'APP-101',
    type: 'Purchase',
    referenceNumber: 'PO-2026-4401',
    requestedBy: 'David Vance (Procurement)',
    department: 'Procurement & Supply',
    amount: 120000,
    date: '2026-09-19',
    title: 'Purchase Order for ABC Traders',
    details: '100 units of Product A (Sensors) and 50 units of Product B (Bearings) to replenish critical safety inventory.',
    status: 'Pending',
    priority: 'High',
  },
  {
    id: 'APP-102',
    type: 'Expense',
    referenceNumber: 'EXP-2026-088',
    requestedBy: 'Priya Sharma (R&D)',
    department: 'Engineering',
    amount: 42500,
    date: '2026-09-18',
    title: 'Field Testing Calibrations & Travel',
    details: 'On-site sensor array benchmark visit to client offshore test plant. Receipts verified.',
    status: 'Pending',
    priority: 'Medium',
  },
  {
    id: 'APP-103',
    type: 'Leave',
    referenceNumber: 'LV-2026-034',
    requestedBy: 'Marcus Sterling',
    department: 'Operations & Logistics',
    date: '2026-09-18',
    title: 'Annual Vacation Leave (5 Days)',
    details: 'Dates requested: Sept 28 - Oct 02. Shift handover assigned to Linda Chen.',
    status: 'Pending',
    priority: 'Low',
  },
  {
    id: 'APP-104',
    type: 'Payment',
    referenceNumber: 'PAY-2026-221',
    requestedBy: 'Sandra Bullock (Accounts)',
    department: 'Finance',
    amount: 280000,
    date: '2026-09-17',
    title: 'Continental Steels Milestone Payment',
    details: 'Final 30% milestone release against verified Goods Receipt Note GRN-1048.',
    status: 'Pending',
    priority: 'High',
  },
  {
    id: 'APP-105',
    type: 'Stock adjustment',
    referenceNumber: 'ADJ-2026-012',
    requestedBy: 'Warehouse Supv. Thomas',
    department: 'Inventory',
    date: '2026-09-16',
    title: 'Quarterly Physical Count Variance Correction',
    details: 'Write-off of 3 damaged casing seals and +5 discovered connector harnesses.',
    status: 'Pending',
    priority: 'Medium',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'NOT-1',
    title: 'Action Required: Purchase Order PO-4401',
    message: 'David Vance submitted PO for ABC Traders (₹1,20,000) requiring Manager sign-off.',
    category: 'Approval',
    timestamp: '10 mins ago',
    read: false,
    actionUrl: '/approvals',
  },
  {
    id: 'NOT-2',
    title: 'Low Stock Alert: Industrial Sensor Module B3',
    message: 'Stock level dropped to 14 units (reorder threshold 50).',
    category: 'Inventory',
    timestamp: '45 mins ago',
    read: false,
    actionUrl: '/inventory',
  },
  {
    id: 'NOT-3',
    title: 'Overdue Invoice Reminder',
    message: 'Zenith Marine Works invoice INV-7712 (₹4,20,000) is now 32 days past due date.',
    category: 'Finance',
    timestamp: '2 hours ago',
    read: false,
    actionUrl: '/finance',
  },
  {
    id: 'NOT-4',
    title: 'AI Monthly Sales Trend Completed',
    message: 'September sales pacing 18.5% above August. AI executive report generated.',
    category: 'AI insights',
    timestamp: '5 hours ago',
    read: true,
    actionUrl: '/reports',
  },
  {
    id: 'NOT-5',
    title: 'New Leave Application',
    message: 'Marcus Sterling requested 5 days annual leave from Sept 28.',
    category: 'HR',
    timestamp: 'Yesterday',
    read: true,
    actionUrl: '/approvals',
  },
];

export const mockSalesChartData = [
  { month: 'Apr', sales: 320000, purchases: 210000, profit: 110000 },
  { month: 'May', sales: 410000, purchases: 290000, profit: 120000 },
  { month: 'Jun', sales: 380000, purchases: 240000, profit: 140000 },
  { month: 'Jul', sales: 520000, purchases: 310000, profit: 210000 },
  { month: 'Aug', sales: 490000, purchases: 280000, profit: 210000 },
  { month: 'Sep', sales: 580000, purchases: 340000, profit: 240000 },
];
